version: "3.9"

services:
  build-service:
    container_name: build
    image: maven:3.6.3-openjdk-8-slim
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean package
    restart: no

  run-service:
    container_name: run
    image: tomcat:9.0-jre8-openjdk-slim
    ports:
      - "8888:8080"
    depends_on:
      build-service:
        condition: service_completed_successfully
    volumes:
      - ./target/hello-1.0.war:/usr/local/tomcat/webapps/app.war
    restart: always
